### ISSUE TITLE
Need Help setting up bot

### ISSUE THREAD

**Issue by Considerated** [Brandon-The-Dev/Hydra#5]
Can someone and/or the owner help me set up the bot? I've done all the setting up like in the file .env, it has both token and the MONGODB URI. But I can't figure out how to do it. It gives me this error:
```bash
(node:155) UnhandledPromiseRejectionWarning: Error: 401 Unauthorized
    at IncomingMessage.<anonymous> (/home/runner/nodeco/node_modules/dblapi.js/src/index.js:118:25)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:155) UnhandledPromiseRejectionWarning: MongoError: bad auth : Authentication failed.
    at MessageStream.messageHandler (/home/runner/nodeco/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/home/runner/nodeco/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/runner/nodeco/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.ondata (_stream_readable.js:718:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
(node:155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Someone please help, I'm trying to set this bot up. @Brandon-The-Dev

**Comment by Brandon-The-Dev** [comment]
You need to // all of the top.gg api

**Comment by Considerated** [comment]
You mean add TopGG api?? Let me try that, thank you.

**Comment by Brandon-The-Dev** [comment]
You done now ?

**Comment by Considerated** [comment]
Man, I'm sorry, I don't know how to get an API, could you help me with that?

**Comment by Brandon-The-Dev** [comment]
You just need to put // before it as you don’t have a bot authorised with TOP.GG

**Comment by Brandon-The-Dev** [comment]
Or you can just remove the DBL info
