### ISSUE TITLE
Issue setting up the bot

### ISSUE THREAD

**Issue by ofcansh** [Brandon-The-Dev/Hydra#6]
I did the .env file added token and monodb uri then too some errors..

(node:227) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/home/runner/UsableNoxiousParallelcompiler/node_modules/mongoose/lib/connection.js:651:11)
    at /home/runner/UsableNoxiousParallelcompiler/node_modules/mongoose/lib/index.js:341:10
    at /home/runner/UsableNoxiousParallelcompiler/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/runner/UsableNoxiousParallelcompiler/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose.connect (/home/runner/UsableNoxiousParallelcompiler/node_modules/mongoose/lib/index.js:340:10)
    at new MongoClient (/home/runner/UsableNoxiousParallelcompiler/src/utils/MongoClient.js:10:18)
    at Object.<anonymous> (/home/runner/UsableNoxiousParallelcompiler/src/index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
(node:227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:227) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error: ENOENT: no such file or directory, scandir './src/commands/'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: './src/commands/'
}
/home/runner/UsableNoxiousParallelcompiler/src/utils/handlers/command.js:6
        const file = files.filter(f => f.split('.').pop() === 'js');
                           ^

TypeError: Cannot read property 'filter' of undefined
    at /home/runner/UsableNoxiousParallelcompiler/src/utils/handlers/command.js:6:28
    at FSReqCallback.oncomplete (fs.js:156:23)

**Comment by johntaxmi** [comment]
Your `.env` file must look something like that:
```
TOKEN=
MONGODB=
```

And just paste your token exactly after the `TOKEN=` and your MongoDB path exactly after `MONGODB=` 
Without Adding anything else, without space and without `''`.

**Comment by ofcansh** [comment]
ok i did that but a new error occured..bot is online but this error in console

(node:189) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'postStats' of undefined
    at module.exports (/home/runner/ecobot/Hydra/src/events/guildCreate.js:38:16)
    at MongoClient.emit (events.js:314:20)
    at Object.module.exports [as GUILD_CREATE] (/home/runner/ecobot/Hydra/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:33:14)
    at WebSocketManager.handlePacket (/home/runner/ecobot/Hydra/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/ecobot/Hydra/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/ecobot/Hydra/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/ecobot/Hydra/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/runner/ecobot/Hydra/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/runner/ecobot/Hydra/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/runner/ecobot/Hydra/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/runner/ecobot/Hydra/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/runner/ecobot/Hydra/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
(node:189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by johntaxmi** [comment]
Ah, guys don't copy-paste a bot and wish it works, learn some basics things first.
That's because of the top.gg API that you haven't add. You need to remove the line of code that requires things for top.gg.

**Comment by Brandon-The-Dev** [comment]
Need to just remove the DBLapi stuff

**Comment by ofcansh** [comment]
> Ah, guys don't copy-paste a bot and wish it works, learn some basics things first.
> That's because of the top.gg API that you haven't add. You need to remove the line of code that requires things for top.gg.

already did that in index.js

**Comment by ofcansh** [comment]
![image_2021-03-27_182258](https://user-images.githubusercontent.com/74647041/112721382-76883080-8f29-11eb-9f87-9959ae1dcea9.png)

**Comment by ofcansh** [comment]
should i also do that for 

const DBL = require("dblapi.js");

?

**Comment by Brandon-The-Dev** [comment]
Yes and then go to the guild-create file and remove the post stats when it joins or leaves a server

**Comment by ofcansh** [comment]
and how can i change the prefix?

like i want some symbol..
or instead of h i want pls, earn something like that

**Comment by ofcansh** [comment]
nvm just discovered it..

**Comment by ofcansh** [comment]
how can i set money for a member like command like addmoney or doing so changes in the userdata file??

**Comment by ofcansh** [comment]
like there are 3 members and i want to give 1 member 100 coins and i dont have sufficient balance then how can i set  user balance of that member??

**Comment by ofcansh** [comment]
nvm just discovered that too... :)

**Comment by ofcansh** [comment]
![image_2021-03-28_180232](https://user-images.githubusercontent.com/74647041/112752267-c7625c80-8fef-11eb-9bef-d39a3e2a63f3.png)

How can i change that HYDRA_RIFLE... i did all changes in items.js and all file and is showing correctly in h shop... but not in h inv..

**Comment by ofcansh** [comment]
![image_2021-03-28_181658](https://user-images.githubusercontent.com/74647041/112752678-caf6e300-8ff1-11eb-9177-020840c6daf8.png)

h shop photo where Hydra_rifle is showing correctly...

**Comment by Brandon-The-Dev** [comment]
As you don’t have the emojis the bot image system is built around the support server as it requires the emojis in that server so unless your bot is in the support server you will have to change all the emojis.

**Comment by ofcansh** [comment]
already did that... its working in shop but not in inv

**Comment by Brandon-The-Dev** [comment]
What ?

**Comment by freeh4ckcompany** [comment]
how can i add topgg stuff to the bot

**Comment by ofcansh** [comment]
When i add my bot to a new server this error in console:

(node:85) UnhandledPromiseRejectionWarning: RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number.
    at Function.resolve (/home/runner/Earn/node_modules/discord.js/src/util/BitField.js:150:19)
    at Permissions.has (/home/runner/Earn/node_modules/discord.js/src/util/BitField.js:45:28)
    at Permissions.has (/home/runner/Earn/node_modules/discord.js/src/util/Permissions.js:45:85)
    at /home/runner/Earn/src/events/guildCreate.js:19:41
    at Map.forEach (<anonymous>)
    at module.exports (/home/runner/Earn/src/events/guildCreate.js:17:22)
    at MongoClient.emit (events.js:314:20)
    at Object.module.exports [as GUILD_CREATE] (/home/runner/Earn/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:33:14)
    at WebSocketManager.handlePacket (/home/runner/Earn/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/Earn/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/Earn/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/Earn/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/runner/Earn/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/runner/Earn/node_modules/ws/lib/receiver.js:437:14)
(node:85) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:85) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:85) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/runner/Earn/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Earn/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:85) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by Brandon-The-Dev** [comment]
What have you edited ?

**Comment by ofcansh** [comment]
nothing except doc url invite url vote... added forest.js to use axe with 4 types of tree and item.js item prices

**Comment by Brandon-The-Dev** [comment]
What’s your top.gg link ?

**Comment by ofcansh** [comment]
https://top.gg/id/vote

but my bot is not yet approved on top.gg

**Comment by Brandon-The-Dev** [comment]
Are you using my code in your bot ?

**Comment by ofcansh** [comment]
Upgrading the bot using your logic... but yea

Can you tell how can i do that h rich showing total net worth instead of coins in wallet

**Comment by ofcansh** [comment]
mm so you discovered me!! ggs but i think you lack of some commands like forest to use axe.. auction house.. discount more items and their uses.. you should add it or shall i implement it and you use it in your bot.. maybe that would be great.

**Comment by ofcansh** [comment]
peace
